name: iOS starter workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.read)['project']['schemes'].first")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build and Test
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
            file_to_build=$(find . -name "*.xcworkspace" -maxdepth 1)
            build_command="build-for-testing"
          else
            file_to_build=$(find . -name "*.xcodeproj" -maxdepth 1)
            build_command="build"
          fi

          default_scheme=$(cat default)
          xcodebuild $build_command -scheme "$default_scheme" -destination "platform=iOS Simulator,name=iPhone 15 Pro"
